### ISSUE TITLE
Fallo al compilar 0.2.3-SNAPSHOT

### ISSUE THREAD

**Issue by katnatek** [universitatjaumei/jxades#14]
Estoy tratando de compilar una version mas reciente del clienteafirma el cual depende de su proyecto, 
pero como no existe un archivo jar para la version 0.2.3-SNAPSHOT en el repositorio de maven,
tengo que compilarlo a mano, pero al intentarlo obtengo:

+ mvn dependency:resolve
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for es.uji.crypto.xades:jxades:jar:0.2.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-jarsigner-plugin @ line 125, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------------< es.uji.crypto.xades:jxades >---------------------
[INFO] Building jXAdES 0.2.3-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:resolve (default-cli) @ jxades ---
[INFO] 
[INFO] The following files have been resolved:
[INFO]    org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO]    junit:junit:jar:4.13.1:compile
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.362 s
[INFO] Finished at: 2021-03-31T12:24:55-06:00
[INFO] ------------------------------------------------------------------------
+ /usr/bin/python3 /usr/share/java-utils/mvn_build.py --xmvn-javadoc --skip-tests --skip-javadoc
Executing: xmvn --batch-mode --offline -Dmaven.test.skip=true package org.fedoraproject.xmvn:xmvn-mojo:install org.fedoraproject.xmvn:xmvn-mojo:builddep
['xmvn', '--batch-mode', '--offline', '-Dmaven.test.skip=true', 'package', 'org.fedoraproject.xmvn:xmvn-mojo:install', 'org.fedoraproject.xmvn:xmvn-mojo:builddep']
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for es.uji.crypto.xades:jxades:jar:0.2.3-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-jarsigner-plugin @ line 125, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------------< es.uji.crypto.xades:jxades >---------------------
[INFO] Building jXAdES 0.2.3-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ jxades ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Using 'null' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ jxades ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 121 source files to /home/katnatek/rpm/BUILD/AutoFirma-1.7.0/jxades-master/target/classes
[INFO] /home/katnatek/rpm/BUILD/AutoFirma-1.7.0/jxades-master/src/main/java/es/uji/crypto/xades/jxades/util/UniversalIndexKey.java: Some input files use unchecked or unsafe operations.
[INFO] /home/katnatek/rpm/BUILD/AutoFirma-1.7.0/jxades-master/src/main/java/es/uji/crypto/xades/jxades/util/UniversalIndexKey.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ jxades ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ jxades ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ jxades ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ jxades ---
[INFO] Building jar: /home/katnatek/rpm/BUILD/AutoFirma-1.7.0/jxades-master/target/jxades-0.2.3-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-jarsigner-plugin:3.0.0:sign (sign) @ jxades ---
[WARNING] The POM for org.apache.maven.shared:maven-jarsigner:jar:3.0.0 is missing, no dependency information available
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Skipping jXAdES
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.925 s
[INFO] Finished at: 2021-03-31T12:25:13-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] UndeclaredThrowableException: InvocationTargetException: Plugin org.apache.maven.plugins:maven-jarsigner-plugin:3.0.0 or one of its dependencies could not be resolved: Cannot access central (https://repo.maven.apache.org/maven2) in offline mode and the artifact org.apache.maven.shared:maven-jarsigner:jar:3.0.0 has not been downloaded from it before.
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by clawgrip** [comment]
Acabo de actualizar el POM, por favor, pruebe ahora.
Muchas gracias.

**Comment by katnatek** [comment]
Compila pero me produce varias veces estos errores

javadoc: warning - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/7/docs/api/ are in the unnamed module.
/home/katnatek/rpm/BUILD/jxades-master/src/main/java/es/uji/crypto/xades/jxades/security/xml/XAdES/SignaturePolicyIdentifierDetails.java:13: error: malformed HTML
 * <xades:SignaturePolicyIdentifier> <xades:SignaturePolicyId> <xades:SigPolicyId>
   ^
Y durante la compilación
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!

**Comment by clawgrip** [comment]
Son errores menores que no afectan a la compilación. Están ya corregidos de todas formas, por favor, pruebe de nuevo y así cierro el issue.

**Comment by katnatek** [comment]
Ya no manda los errores, gracias.
Por favor pongan una nota de como se debe construir este proyecto, tuve que encontrar por ensayo y error
