### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mauroooooooo** [universitatjaumei/jxades#6]
Hi, i need to change all the digest method to SHA-256

I maded with the first 2 with this sentences:

xmlSignature.setDigestMethod(DigestMethod.SHA256);
xmlSignature.sign(opcionesFirma.getCertificate(), opcionesFirma.getPrivateKey(),
                "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256", Arrays.asList(new Object[] {}), "FE");

<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>

But almost at the end of the signature there is another:

<xades:CertDigest><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>

Also i need to see if there is possible to add the following

<xades:SignaturePolicyIdentifier>
	<xades:SignaturePolicyId>
		<xades:SigPolicyId>
			<xades:Identifier>
				https://tribunet.hacienda.go.cr/docs/esquemas/2016/v4/Resolucion%20Comprobantes%20Electronicos%20%20DGT-R-48-2016.pdf
			</xades:Identifier>
			<xades:Description />
		</xades:SigPolicyId>
		<xades:SigPolicyHash>
			<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
			<ds:DigestValue>
				Ohixl6upD6av8N7pEvDABhEL6hM=
			</ds:DigestValue>
		</xades:SigPolicyHash>
	</xades:SignaturePolicyId>
</xades:SignaturePolicyIdentifier>

because right now it looks like the following

<xades:SignaturePolicyIdentifier>
      <xades:SignaturePolicyImplied/>
        
</xades:SignaturePolicyIdentifier>

Thanks in advance

**Comment by developerAndroid098** [comment]
@mauroooooooo  - did you resolve this issue ?

**Comment by clawgrip** [comment]
The issue about chaging the digest method is fixed. Please, open a separate one for the other issue about policies.
